language: objective-c
osx_image: xcode9.2
# branches:
#   only:
#     - test_travis
if: tag IS present
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - FRAMEWORK_NAME=${TRAVIS_TAG%%.*}
  - FRAMEWORK_ZIP="$FRAMEWORK_NAME.framework.zip"
# Install carthage
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
install:
  - echo "$TRAVIS_TAG" & echo "$FRAMEWORK_NAME" & echo "$FRAMEWORK_ZIP"
  - cd "$FRAMEWORK_NAME" & pwd
  - chmod +x ../update_self.sh & ../update_self.sh
script:
  - echo "Run test"

before_deploy:
  - carthage build --no-skip-current
  - carthage archive "$FRAMEWORK_NAME"

deploy:
  provider: releases
  api_key: e95f93d6ba660517b2b7bda656944792e36a3ea2
  file: "$FRAMEWORK_ZIP"
  skip_cleanup: true
  on:
    repo: CanyFrog/HIComponents
    tags: true

