source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'HQKit' do
  pod 'HQFoundation', :path=>'../HQFoundation.podspec'

  target 'HQKitDemo' do
    inherit! :search_paths
  end
end