source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'HQKit' do
  # pod 'HQFoundation', :path=>'../HQFoundation.podspec'
  pod 'HQFoundation', '~> 2018.0' 

  target 'HQKitDemo' do
    inherit! :search_paths
  end
end