# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HQCache' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'HQSqlite', '~> 2018.0'
  pod 'HQFoundation', '~> 2018.0'

  # Pods for HQCache

  target 'HQCacheTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
